/* eslint-disable */
/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require("fs");
const { join } = require("path");

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
	// For Node 12, we use `ldd` to detect if the system is musl-based
	if (!process.report || typeof process.report.getReport !== "function") {
		try {
			const lddPath = require("child_process")
				.execSync("which ldd")
				.toString()
				.trim();
			return readFileSync(lddPath, "utf8").includes("musl");
		} catch {
			return true;
		}
	} else {
		const { glibcVersionRuntime } = process.report.getReport().header;
		return !glibcVersionRuntime;
	}
}

switch (platform) {
	case "darwin":
		switch (arch) {
			case "x64":
				localFileExisted = existsSync(join(__dirname, "aec.darwin-x64.node"));
				try {
					if (localFileExisted) {
						nativeBinding = require("./aec.darwin-x64.node");
					} else {
						nativeBinding = require("agent-voice-aec-darwin-x64");
					}
				} catch (e) {
					loadError = e;
				}
				break;
			case "arm64":
				localFileExisted = existsSync(join(__dirname, "aec.darwin-arm64.node"));
				try {
					if (localFileExisted) {
						nativeBinding = require("./aec.darwin-arm64.node");
					} else {
						nativeBinding = require("agent-voice-aec-darwin-arm64");
					}
				} catch (e) {
					loadError = e;
				}
				break;
			default:
				throw new Error(`Unsupported architecture on macOS: ${arch}`);
		}
		break;
	case "linux":
		switch (arch) {
			case "x64":
				if (isMusl()) {
					throw new Error("musl libc is not supported");
				} else {
					localFileExisted = existsSync(
						join(__dirname, "aec.linux-x64-gnu.node"),
					);
					try {
						if (localFileExisted) {
							nativeBinding = require("./aec.linux-x64-gnu.node");
						} else {
							nativeBinding = require("agent-voice-aec-linux-x64-gnu");
						}
					} catch (e) {
						loadError = e;
					}
				}
				break;
			case "arm64":
				if (isMusl()) {
					throw new Error("musl libc is not supported");
				} else {
					localFileExisted = existsSync(
						join(__dirname, "aec.linux-arm64-gnu.node"),
					);
					try {
						if (localFileExisted) {
							nativeBinding = require("./aec.linux-arm64-gnu.node");
						} else {
							nativeBinding = require("agent-voice-aec-linux-arm64-gnu");
						}
					} catch (e) {
						loadError = e;
					}
				}
				break;
			default:
				throw new Error(`Unsupported architecture on Linux: ${arch}`);
		}
		break;
	default:
		throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
	if (loadError) {
		throw loadError;
	}
	throw new Error(`Failed to load native binding`);
}

const { EchoCanceller } = nativeBinding;

module.exports.EchoCanceller = EchoCanceller;
